name: Super-Linter

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install poetry
          make install
      - name: Run linter and pytest
        run: |
          make lint
      - name:  Coverage report 
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: dca68d8a96676d608132cc9b139fa275bd50d37dc6118b6ee0a484306d949fd6
        with:
          coverageCommand: make coverage